[package]
name = "egui-table-issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.20.0"
eframe = "0.20.0"
egui_extras = { version="0.20.0", features = ["image"] }